export {default as About} from './about'
export {default as Experience} from './experience'
export {default as Tech} from './tech'
export {default as Works} from './works'
export {default as Contact} from './contact'